  
name: pokedex
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  percent_indicator: "^2.1.1"
  flutter_mobx: ^0.3.3+1
  mobx: ^0.3.9+1
  dio: ^3.0.0
  rxdart: ^0.22.6
  bloc_pattern: ^2.5.1
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mobx_codegen: ^0.3.10
  build_runner: ^1.7.2
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets: 
    - lib/app/shared/assets/images/

scripts:
  build: flutter pub run build_runner build
  clean: flutter pub run build_runner clean